---
#- name: Add PHP 7 repository from PPA
#  become: yes
#  apt_repository:
#    validate_certs: no
#    repo: ppa:ondrej/php
#  tags:
#    - php8.1

- name: Install PHP 8.1 packages
  become: yes
  apt:
    name:
      - php8.1
      - php8.1-cli
      - php8.1-curl
      - php8.1-gd
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-odbc
      - php8.1-xml
      - php8.1-zip
      - php8.1-bz2
      - php8.1-intl
      - php8.1-apcu
      - php8.1-redis
      - php8.1-msgpack
      - php8.1-imagick
      - php-pear
      - php8.1-sybase
      - php8.1-xdebug
    state: fixed
  notify: Restart Apache2
  tags:
    - php8.1

- name: Insert xdebug configuration
  become: yes
  become_method: sudo
  blockinfile:
    dest: /etc/php/8.1/mods-available/xdebug.ini
    block: |
      xdebug.mode=debug
      xdebug.client_host=10.0.2.2
      xdebug.client_port=9003
  tags:
    - php8.1

- name: Set PHP configuration in php.ini
  become: yes
  ini_file:
    path: /etc/php/8.1/apache2/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: PHP, option: memory_limit, value: 512M }
    - { section: PHP, option: max_execution_time, value: 100 }
    - { section: PHP, option: max_input_time, value: 100 }
    - { section: PHP, option: upload_max_filesize, value: 100M }
    - { section: PHP, option: post_max_size, value: 100M }
    - { section: Date, option: date.timezone, value: Europe/Stockholm }
  notify: Restart Apache2
  tags:
    - php8.1

- name: Set Lucatopen.lu.se server configuration to freeTDS config file
  become: yes
  blockinfile:
    path: /etc/freetds/freetds.conf
    block: |
      [lucatopen.lu.se]
              host = lucatopen.lu.se
              port = 1433
              use ntlmv2 = yes
              tds version = 8.0
              client charset = UTF-8
  tags:
    - ehl